// <auto-generated />
using System;
using CBTSWE2.TP03.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CBTSWE2.TP03.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20260930232009_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CBTSWE2.TP03.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Notebook com processador Intel Core i5, 8 GB de RAM e SSD de 256 GB.",
                            Nome = "Notebook Dell Inspiron 15",
                            Preco = 3499.90m,
                            QuantidadeEstoque = 12
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2026, 9, 2, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mouse óptico sem fio com receptor USB e alcance de até 10 metros.",
                            Nome = "Mouse sem fio Logitech M170",
                            Preco = 59.90m,
                            QuantidadeEstoque = 80
                        },
                        new
                        {
                            Id = 3,
                            DataCadastro = new DateTime(2026, 9, 3, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Teclado mecânico ABNT2 com switches outemu blue e iluminação LED vermelha.",
                            Nome = "Teclado mecânico Redragon Kumara",
                            Preco = 229.00m,
                            QuantidadeEstoque = 5
                        },
                        new
                        {
                            Id = 4,
                            DataCadastro = new DateTime(2026, 9, 4, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Monitor IPS Full HD de 24 polegadas com entrada HDMI e DisplayPort.",
                            Nome = "Monitor LG 24 polegadas",
                            Preco = 899.00m,
                            QuantidadeEstoque = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
